### ISSUE TITLE
visfile.times

### ISSUE THREAD

**Issue by lijingwang** [pinshuai/modvis#2]
### Environment Information

modvis version: 0.0.1
Python version: python3.10
Operating System: Mac

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

Do visualization for a long cold spinup. 

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

Hi modvis team, 

I want to visualize a cold spin up which has around 20000 days using  pv.plot_surface_data. However, it said that 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [27], in <cell line: 1>()
----> 1 fig, ax, tpc = pv.plot_surface_data(visfile, var_name="surface-ponded_depth", 
      2                                     log = True, vmin=0.0001, vmax=0.1, 
      3                                     time_slice=1, origin_date="0001-01-01")

File ~/anaconda3/envs/watershed_workflow-2022-08-29/lib/python3.10/site-packages/modvis/plot_vis_file.py:511, in plot_surface_data(vis_data, var_name, origin_date, time_slice, facecolors, subset, subset_idx, colorbar, clabel, title, ax, log, vmin, vmax, robust, contour, nlevel, linthresh, linscale, data_lim, **kwargs)
    508 conn = vis_data.conn
    509 volume = vis_data.volume
--> 511 times, time_idx = get_time(vis_data, time_slice, origin_date=origin_date)
    513 if isinstance(var_name, str):
    514     dat = vis_data.getArray(var_name)

File ~/anaconda3/envs/watershed_workflow-2022-08-29/lib/python3.10/site-packages/modvis/plot_vis_file.py:53, in get_time(vis_data, time_slice, **kwargs)
     51 """get time index if time_slice is str formatted"""
     52 times = vis_data.times
---> 53 times = rmLeapDays(times, **kwargs)
     55 if time_slice is not None:
     56     try:

File ~/anaconda3/envs/watershed_workflow-2022-08-29/lib/python3.10/site-packages/modvis/ATSutils.py:398, in rmLeapDays(time_ats, origin_date, noleap, freq)
    396 else:
    397     raise RuntimeError("Must be either D or H freq!")
--> 398 model_start_date = origin_date.replace(year = origin_date.year + int(model_start_year))
    399 model_start_date = model_start_date + timedelta(days = int(model_start_doy))
    401 if freq == 'D':
ValueError: year 20184 is out of range. 

So apparently the visfile.times are very large in my case: [7001842.5, 7012800. , 7023757.5, 7034715. , 7045672.5, 7056630. ,
       7067587.5, 7078545. , ]

But when I visualize water_balance.dat without using modvis, the time is around 20000 days without a problem. I am wondering what the visfile.times actually return, and how I might adjust the time to visualize my 3D mesh. Thank you! 

Best,
Lijing.

**Comment by pinshuai** [comment]
Hi Lijing,

Can you print `visfile.times` and `visfile.cycles` after loading the mesh using `visfile=xdmf.VisFile()`? I suspect the time unit in the h5 file is in 'day' instead of 'year'.

Pin

**Comment by lijingwang** [comment]
Yes exactly. If I check the visfile.times it will give me a very large
number. The actual days I am using is this visfile.times/365.25, starting
from 11223 days (the number of days to 1980-01-01). Is there an automatic
multiplication with 365.25 in the visfile load?

Thanks, Lijing.

[image: image.png]

[image: image.png]
------------------------------------------------------------------------
------------------------------------
Lijing Wang

Ph.D., Department of Earth and Planetary Sciences

Stanford University

***@***.***

**Comment by pinshuai** [comment]
Please use `xdmf.VisFile(model_time_unit='d')` . The time unit defaults to 'year'.

**Comment by lijingwang** [comment]
Thanks Pin! That works perfectly.

Best,
Lijing.
------------------------------------------------------------------------
------------------------------------
Lijing Wang

Ph.D., Department of Earth and Planetary Sciences

Stanford University

***@***.***
